default_language_version:
    python: python3.6

repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
    -   id: check-ast
    -   id: check-json
    -   id: check-merge-conflict
    -   id: detect-private-key
    -   id: check-toml
    -   id: debug-statements
    -   id: pretty-format-json
        args:
            - "--autofix"
            - "--indent=4"
            - "--no-sort-keys"

-   repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
    -   id: flake8
        additional_dependencies: [flake8-docstrings]
        args: ['--max-line-length=100']

-   repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
    -   id: isort
        args: ['--profile', 'black']

-   repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
    -   id: black
        args: ['--line-length=100']

-   repo: https://github.com/hhatto/autopep8
    rev: v2.3.1  # select the tag or revision you want, or run `pre-commit autoupdate`
    hooks:
    -   id: autopep8
        args:
            - "--in-place"
