site_name: PyTau
site_description: "Simple python package to perform streamlined batch inference on changepoint models"

theme:
  name: "material"
  palette:
    primary: "blue"
    accent: "grey"
  features:
      - toc.integrate
      - navigation.sections

plugins:
  - search
  - mkdocstrings

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences

nav:
  - "Start": index.md
  - "API": api.md
